# Generated by Django 4.2 on 2025-02-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alunos",
            name="nascimento",
            field=models.DateField(null=True),
        ),
    ]
