# Generated by Django 4.2 on 2025-02-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0002_alunos_nascimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="ano_publicacao",
            field=models.DateField(),
        ),
    ]
