# Generated by Django 4.2 on 2025-02-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0003_alter_livros_ano_publicacao"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Alunos",
            new_name="Aluno",
        ),
        migrations.RenameModel(
            old_name="Livros",
            new_name="Livro",
        ),
        migrations.CreateModel(
            name="Tiragem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("isbn", models.IntegerField()),
                (
                    "livro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="livro",
                        to="library_app.livro",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="aluno",
            name="tiragem",
            field=models.ManyToManyField(
                through="library_app.Emprestimo", to="library_app.tiragem"
            ),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="tiragem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="library_app.tiragem"
            ),
        ),
        migrations.DeleteModel(
            name="Tiragens",
        ),
    ]
