# Generated by Django 4.2 on 2025-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "library_app",
            "0004_rename_alunos_aluno_rename_livros_livro_tiragem_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="sobrenome",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
