# Generated by Django 4.2 on 2025-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0005_aluno_sobrenome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="sobrenome",
            field=models.CharField(max_length=150),
        ),
    ]
