# Generated by Django 4.2 on 2025-02-28 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0006_alter_aluno_sobrenome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiragem",
            name="livro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tiragens",
                to="library_app.livro",
            ),
        ),
    ]
