# Generated by Django 4.2 on 2025-03-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0007_alter_tiragem_livro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_devolucao",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="data_emprestimo",
            field=models.DateField(),
        ),
    ]
