# Generated by Django 4.2 on 2025-03-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0008_alter_emprestimo_data_devolucao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_devolucao",
            field=models.DateField(null=True),
        ),
    ]
