# Generated by Django 4.2 on 2025-03-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0009_alter_emprestimo_data_devolucao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_devolucao",
            field=models.DateField(),
        ),
    ]
