# Generated by Django 4.2 on 2025-03-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0011_alter_emprestimo_data_devolucao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_devolucao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
