# Generated by Django 4.2 on 2025-03-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0012_alter_emprestimo_data_devolucao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiragem",
            name="isbn",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
