# Generated by Django 4.2 on 2025-03-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0013_alter_tiragem_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="ano_publicacao",
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
