# Generated by Django 4.2 on 2025-03-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0014_alter_livro_ano_publicacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiragem",
            name="disponivel",
            field=models.BooleanField(default=True),
        ),
    ]
