# Generated by Django 4.2 on 2025-03-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0015_tiragem_disponivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="ano_publicacao",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
