# Generated by Django 4.2 on 2025-03-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0016_alter_livro_ano_publicacao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emprestimo",
            old_name="data_devolucao",
            new_name="dt_devolucao",
        ),
        migrations.RenameField(
            model_name="emprestimo",
            old_name="data_emprestimo",
            new_name="dt_emprestimo",
        ),
    ]
