# Generated by Django 4.2 on 2025-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0017_rename_data_devolucao_emprestimo_dt_devolucao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="email",
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="endereco",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
